import Config

# THE DATABASE ARRIVES. This app was fixtures-only until the passport needed
# somewhere to keep a hashed word bank, and Postgres is the choice because the
# domain is relational to its bones: a scope is a row joining two people, and a
# letter is a row hanging off a scope.
config :peoplemedia, Peoplemedia.Repo,
  username: System.get_env("PGUSER") || "postgres",
  password: System.get_env("PGPASSWORD") || "postgres",
  hostname: "localhost",
  database: "peoplemedia_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :peoplemedia, PeoplemediaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NAeOUMEahKvG+JS+zFCPT4DtYuX3enUqLDMOUGYxVdbviRDo7qbJ0AmA6lkojjbF",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:peoplemedia, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:peoplemedia, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :peoplemedia, PeoplemediaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/peoplemedia_web/router\.ex$",
      ~r"lib/peoplemedia_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :peoplemedia, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# ── THE MASTER PASSPORT ───────────────────────────────────────────────────────
# One handle whose one-time words are NOT spent when they are used, so there is
# an account you can check into over and over while working on the thing.
#
# IT LIVES HERE RATHER THAN IN THE CODE because it is the passport scheme turned
# off for one account, and a hole like that has to be visible and switchable. Set
# to nil — or simply absent, which is the default — and every word burns.
#
#     name: angel    word: angel    code: 0000
config :peoplemedia, master_handle: "angel"
