import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :peoplemedia, PeoplemediaWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :peoplemedia, PeoplemediaWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    # paths: ["/health"],
    hosts: ["localhost", "127.0.0.1"]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# THE MASTER PASSPORT, and it is in the PRODUCTION config on purpose while this
# app is still a demonstration of itself — the deployed copy is something to be
# logged into and looked at, not somewhere real people keep anything. It is
# `compile_env`, so it cannot be moved to runtime.exs; it has to be decided when
# the release is built.
#
# THIS LINE GOES the day the first real passport is issued. Until then it is the
# only thing standing between a demo and a locked door.
config :peoplemedia, master_handle: "angel"
